### ISSUE TITLE
editliveos fails after edit completes

### ISSUE THREAD

**Issue by chrisawad** [livecd-tools/livecd-tools#131]
Hi,

I received the following output while running editliveos from master:

> The new image will now be packaged. Please wait...
> Parallel mksquashfs: Using 8 processors
> Creating 4.0 filesystem on /var/tmp/editliveos-pOHSZJ/iso/LiveOS/squashfs.img, block size 131072.
> [==========================================================================================================================================================================================|] 53264/53264 100%
> 
> Exportable Squashfs 4.0 filesystem, xz compressed, data block size 131072
>         compressed data, compressed metadata, compressed fragments, compressed xattrs
>         duplicates are removed
> Filesystem size 1393872.24 Kbytes (1361.20 Mbytes)
>         20.44% of uncompressed filesystem size (6818000.53 Kbytes)
> Inode table size 66022 bytes (64.47 Kbytes)
>         30.96% of uncompressed inode table size (213246 bytes)
> Directory table size 58 bytes (0.06 Kbytes)
>         100.00% of uncompressed directory table size (58 bytes)
> Xattr table size 53 bytes (0.05 Kbytes)
>         100.00% of uncompressed xattr table size (53 bytes)
> Number of duplicate files found 0
> Number of inodes 3
> Number of files 1
> Number of fragments 0
> Number of symbolic links  0
> Number of device nodes 0
> Number of fifo nodes 0
> Number of socket nodes 0
> Number of directories 2
> Number of ids (unique uids + gids) 1
> Number of uids 1
>         root (0)
> Number of gids 1
>         root (0)
> 
> LiveOS edit has completed.
> Process duration: 00:06:32
> Traceback (most recent call last):
>   File "/usr/bin/editliveos", line 2434, in <module>
>     sys.exit(main())
>   File "/usr/bin/editliveos", line 2397, in main
>     editor.package(output, ops)
>   File "/usr/lib/python2.7/site-packages/imgcreate/creator.py", line 829, in package
>     self._stage_final_image(ops)
>   File "/usr/lib/python2.7/site-packages/imgcreate/live.py", line 382, in _stage_final_image
>     self.__create_iso(self.__isodir)
>   File "/usr/lib/python2.7/site-packages/imgcreate/live.py", line 332, in __create_iso
>     if subprocess.call(args) != 0:
>   File "/usr/lib64/python2.7/subprocess.py", line 168, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Everything looks good until the last call (maybe?). Anyone have any ideas what could be breaking? I believe it has something to do with what's in output/ops, passed in from line 2397 in editloveos.

**Comment by FGrose** [comment]
The released version in Fedora 30 will have line 1 adjusted to 
`#!/usr/bin/python3`

That is how I test.  Try that to see if it makes a difference.
