### ISSUE TITLE
27.1 does not work on CentOS 7 1908

### ISSUE THREAD

**Issue by zerocarbthirty** [livecd-tools/livecd-tools#146]
Hi,

When running livecd-creator 27.1 on CentOS 7 on several different hosts I am getting:

Traceback (most recent call last):
  File "/usr/bin/livecd-creator", line 258, in <module>
    sys.exit(main())
  File "/usr/bin/livecd-creator", line 241, in main
    creator.package(ops=ops)
  File "/usr/lib/python2.7/site-packages/imgcreate/creator.py", line 829, in package
    self._stage_final_image(ops)
  File "/usr/lib/python2.7/site-packages/imgcreate/live.py", line 382, in _stage_final_image
    self.__create_iso(self.__isodir)
  File "/usr/lib/python2.7/site-packages/imgcreate/live.py", line 332, in __create_iso
    if subprocess.call(args) != 0:
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any clue what the issue might be?

**Comment by renanrodrigo** [comment]
Same issue here, also for 26.1

**Comment by renanrodrigo** [comment]
Fixed by installing the `squashfs-tools` package.
