### ISSUE TITLE
livecd-creator fails after installing grub2-efi-x64-cdboot

### ISSUE THREAD

**Issue by ycollet** [livecd-tools/livecd-tools#172]
I use livecd-creator on Fedora32.

I updated the config/live-fedora-minimal.ks file from the repo:
```
dracut-live
grub2
grub2-tools
grub2-efi
grub2-efi-x64-cdboot
shim-x64

kernel
kernel-modules
kernel-modules-extra
kernel-tools
```

After installing grub2-efi-x64-cdboot in the ks file:

```
The authconfig command is not available.
Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
success
The 'rhgb' entity is not available.
The '/usr/lib/anaconda-runtime/checkisomd5' entity is not available.
The 'checkisomd5' entity is not available.
The 'rhgb' entity is not available.
The '/usr/lib/anaconda-runtime/checkisomd5' entity is not available.
The 'checkisomd5' entity is not available.
Unmounting directory /var/tmp/imgcreate-rk0djegr/install_root
Losetup remove /dev/loop1
Traceback (most recent call last):
  File "/home/collette/repositories/github/livecd-tools/tools/livecd-creator", line 258, in <module>
    sys.exit(main())
  File "/home/collette/repositories/github/livecd-tools/tools/livecd-creator", line 232, in main
    creator.configure()
  File "/home/collette/repositories/github/livecd-tools/imgcreate/creator.py", line 800, in configure
    self._create_bootconfig()
  File "/home/collette/repositories/github/livecd-tools/imgcreate/live.py", line 259, in _create_bootconfig
    self._configure_bootloader(self.__ensure_isodir())
  File "/home/collette/repositories/github/livecd-tools/imgcreate/live.py", line 843, in _configure_bootloader
    self._configure_efi_bootloader(isodir)
  File "/home/collette/repositories/github/livecd-tools/imgcreate/live.py", line 829, in _configure_efi_bootloader
    cfg += self.__get_efi_image_stanzas(isodir, self.name)
  File "/home/collette/repositories/github/livecd-tools/imgcreate/live.py", line 796, in __get_efi_image_stanzas
    cfg += self.__get_efi_image_stanza(fslabel = self.fslabel,
  File "/home/collette/repositories/github/livecd-tools/imgcreate/live.py", line 774, in __get_efi_image_stanza
    if self._isDracut:
AttributeError: 'x86LiveImageCreator' object has no attribute '_isDracut'
```

**Comment by Conan-Kudo** [comment]
Hmm, I think the `_isDracut` stuff isn't correctly handled...
