### ISSUE TITLE
ModuleNotFoundError: No module named 'errors'

### ISSUE THREAD

**Issue by T-vK** [livecd-tools/livecd-tools#228]
Running `editliveos` or more specifically:

```
    USERNAME="T-vK" sudo editliveos \
    --builder "T-vK" \
    --noshell \
    --script "${TMP_SCRIPT}" \
    --extra-kernel-args "$ALL_KERNEL_PARAMS" \
    --output "${LIVE_ISO_FILES_DIR}" \
    --name "mbpt" \
    "${ISO_FILE}"
```

results in this error:

```
 Traceback (most recent call last):
  File "/usr/bin/editliveos", line 74, in <module>
    from imgcreate.fs import *
  File "/usr/lib/python3.10/site-packages/imgcreate/__init__.py", line 19, in <module>
    from imgcreate.live import *
  File "/usr/lib/python3.10/site-packages/imgcreate/live.py", line 35, in <module>
    from imgcreate.fs import *
  File "/usr/lib/python3.10/site-packages/imgcreate/fs.py", line 35, in <module>
    from imgcreate.util import *
  File "/usr/lib/python3.10/site-packages/imgcreate/util.py", line 23, in <module>
    from errors import *
ModuleNotFoundError: No module named 'errors'
```

My assumption is this is coming from here:

https://github.com/livecd-tools/livecd-tools/blob/09e7dee64357ff890c9015ab022c7ca952d75fae/imgcreate/util.py#L23

I tried installing the module, just like I has to do it with `urlgrabber`, but I got an error:

```
$ sudo pip3 install errors
ERROR: Could not find a version that satisfies the requirement errors (from versions: none)
ERROR: No matching distribution found for errors
```

That `ModuleNotFoundError` error does not occur when using commit [9c7f40e7](https://github.com/livecd-tools/livecd-tools/commit/9c7f40e7edae3475be9a0b8afd7b390a7ad3bfbc).

Any help would be appreciated. At the moment I'm stuck on that old commit that has a bug which removes my kernel parameters forcing me to flash via `livecd-iso-to-disk` so that I can re-specify the kernel parameters that got lost via `--extra-kernel-args`.

**Comment by FGrose** [comment]
try replacing that line 23 in util.py with
```
from imgcreate.errors import *
```
