### ISSUE TITLE
editliveos ----kickstart option won't load i18n or l10n features ( timezone , keyboard, lang) 

### ISSUE THREAD

**Issue by mahdiaqallal** [livecd-tools/livecd-tools#231]
Hi,
First I am a newcomer in Fedora/Linux 
I've tried to use lived-tools for a couple of years now (wonderful tools !) but the sparse documentation is sometimes challenging and might need more elaboration, explanations and examples to be accessible for people with (sometimes very!) limited programming skills. (...So: How can I contribute ?)

One of my basic goals for using livecd-tools is to customize a Fedora Workstation Live Image .iso file from en_US/EST(America) to fr_FR/CEST(Europe)

The kickstart file (my.cfg) I've used is very basic:
```
# Keyboard layouts
keyboard --vckeymap=fr-oss --xlayouts='fr (oss)'

# System language
lang fr_FR.UTF-8

# System timezone
timezone Europe/Paris
```
So the command should be basic:

`sudo editliveos --name Fedora-Workstation-Live-x86_64-32-1.6-FR --tmpdir < tmpdir > --output < dir > --kickstart < my.cfg > <path>/Fedora-Workstation-Live-x86_64-32-1.6.iso`

Commands exits without error `'LiveOS edit has completed. Process duration: 00:18:07"`
But the desired FR version of the .iso file is still en_US/EST(America) and neither in french keyboard, Europe CEST timezone nor in French Language...
What did I do wrong ?...

**Comment by FGrose** [comment]
Unfortunately, `editliveos` has very limited kickstart support.
However, I found that those 3 elements can be supported if the '`if editor.ks:` block (https://github.com/livecd-tools/livecd-tools/blob/fd6225a6c90657d859971af8f3b0ddcff0d40459/tools/editliveos#L2642) is modified as follows:
```python
        if editor.ks:
            # Run_pre_scripts same code as ImageCreator_run_post_scripts
            # editor._run_post_scripts()
            # editor.install()
            ksh = editor.ks.handler

            kickstart.LanguageConfig(editor._instroot).apply(ksh.lang)
            kickstart.KeyboardConfig(editor._instroot).apply(ksh.keyboard)
            kickstart.TimezoneConfig(editor._instroot).apply(ksh.timezone)
            editor._run_post_scripts()
```
Note:  `pykickstart` must be installed on your build system (`sudo dnf install pykickstart`).
Also the `editor.install()` line had to be commented out to prevent the following warning & error:
```sh
warning: Found bdb_ro Packages database while attempting sqlite backend: using bdb_ro backend.
Error editing LiveOS : 'Failed to find group 'core' : no such group: @core'
```
(Probably because the kickstart configuration file lacked the minimal install details.)

**Comment by mahdiaqallal** [comment]
Thank you @FGrose for your answer !

(Please bear in mind I do have little to none programming skill)

> Note: `pykickstart` must be installed on your build system (sudo dnf install pykickstart).

I am running Fedora Silverblue 34 so `pykickstart-3.32-2.fc34.noarch` seems to be installed
```
$ rpm -iq pykickstart
pykickstart-3.32-2.fc34.noarch
```

I have modified the editliveos script as requested:
```
2640         if not editor.refresh_only:
2641             editor._configure_bootloader(editor._LiveImageCreatorBase__isodir)
2642         if editor.ks:
2643             # Run_pre_scripts same code as ImageCreator_run_post_scripts
2644             # editor._run_post_scripts()
2645             # editor.install()
2646             ksh = editor.ks.handler
2647 
2648             kickstart.LanguageConfig(editor._instroot).apply(ksh.lang)
2649             kickstart.KeyboardConfig(editor._instroot).apply(ksh.keyboard)
2650             kickstart.TimezoneConfig(editor._instroot).apply(ksh.timezone)
2651             editor._run_post_scripts()
2652 
2653 #        if editor.ks:
2654 #            # Run_pre_scripts same code as ImageCreator_run_post_scripts
2655 #            # editor._run_post_scripts()
2656 #            editor.install()
2657 #            editor._run_post_scripts()
2658         elif args.script:
2659             print("Running edit script '%s'" % args.script)

```
Is is saved into the updated script `editliveos-30-#231`
The following command does produce following error:

```
$ sudo ~/Images/livecd-toolsLATEST/editliveos-30-#231 --name Fedora-Workstation-Live-x86_64-32-1.6-FR --tmpdir /run/media/mahdiaqallal/home_fedora --output  /run/media/mahdiaqallal/home_fedora --kickstart /home/mahdiaqallal/editliveos-ks_FR.cfg_V01 /run/media/mahdiaqallal/7746-D704/Fedora-Workstation-Live-x86_64-32-1.6.iso 

Source image at '/run/media/mahdiaqallal/7746-D704/Fedora-Workstation-Live-x86_64-32-1.6.iso'

LiveOS edit has ended.
Process duration: 00:00:05
Traceback (most recent call last):
  File "/var/home/mahdiaqallal/Images/livecd-toolsLATEST/editliveos-30-#231", line 2765, in <module>
    sys.exit(main())
  File "/var/home/mahdiaqallal/Images/livecd-toolsLATEST/editliveos-30-#231", line 2626, in main
    editor._pre_mount(args.liveos, args.rootfsimg, args.overlay)
  File "/var/home/mahdiaqallal/Images/livecd-toolsLATEST/editliveos-30-#231", line 751, in _pre_mount
    self._LoopImageCreator__fstype = losm.imgloop.fstype
AttributeError: 'LoopbackDisk' object has no attribute 'fstype'
```
What did I miss ?

**Comment by mahdiaqallal** [comment]
Thank you !

 I will try your proposals, but before I'll have to figure how to update packages in Silverblue for which `dnf` command does not exist....

**Comment by mahdiaqallal** [comment]
I needed to upgrade to Fedora Silverblue 35 to be able to use [livecd-tools-30.0-1.fc35](https://koji.fedoraproject.org/koji/search?terms=livecd-tools-30.0-1.fc35&type=build&match=glob)

Here is the command and it's output:
```
$ sudo ~/editliveos --name Fedora-Workstation-Live-x86_64-35FR-1.6 --tmpdir /var/tmp/ --output  /var/home/mahdi/Vidéos/ --kickstart /var/home/mahdi/editliveos-ks_FR.cfg_V01 /var/home/mahdi/Fedora-Workstation-Live-x86_64-35-1.2.iso 
[sudo] password for mahdi: 

Source image at '/var/home/mahdi/Fedora-Workstation-Live-x86_64-35-1.2.iso'

          183,659,977 extra bytes set to be copied from the sources.
        5,276,937,129 bytes used in the LiveOS filesystem in /var/home/mahdi/Fedora-Workstation-Live-x86_64-35-1.2.iso.

        8,055,160,832 total bytes, root filesystem image size.

        8,351,931,663 bytes are estimated to be required for staging this build.

       40,484,220,928 bytes are available on /var/tmp/ for staging the build.
Copying the included folders and files.
Setting SELinux contexts...
Checking kernel versions in current image...
Checking kernel versions in current .iso...
Launching shell. Exit (Ctrl D) to continue.
-------------------------------------------
[root@fedora /]# 
exit
Checking kernel versions in new .iso...
Checking kernel versions in new install image...
The new image will now be packaged. Please wait...
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Anaconda: 145994/492480 files (0.1% non-contiguous), 1415414/1966080 blocks
 
 e2fsck 1.46.3 (27-Jul-2021)
 
 0
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Anaconda: 145994/467856 files (0.1% non-contiguous), 1413869/1858109 blocks
 
 e2fsck 1.46.3 (27-Jul-2021)
 
 0
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Anaconda: 145994/467856 files (0.1% non-contiguous), 1413869/1858109 blocks
 
 e2fsck 1.46.3 (27-Jul-2021)
 
 0
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Anaconda: 145994/492480 files (0.1% non-contiguous), 1415414/1966080 blocks
 
 e2fsck 1.46.3 (27-Jul-2021)
 
 0
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on /var/tmp/editliveos-4f84t81y/iso/LiveOS/squashfs.img, block size 131072.
[=========================================================================================================================================================================================================================|] 61456/61456 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 1883542.46 Kbytes (1839.40 Mbytes)
	23.94% of uncompressed filesystem size (7866608.54 Kbytes)
Inode table size 84518 bytes (82.54 Kbytes)
	34.35% of uncompressed inode table size (246022 bytes)
Directory table size 58 bytes (0.06 Kbytes)
	100.00% of uncompressed directory table size (58 bytes)
Xattr table size 53 bytes (0.05 Kbytes)
	100.00% of uncompressed xattr table size (53 bytes)
Number of duplicate files found 0
Number of inodes 3
Number of files 1
Number of fragments 0
Number of symbolic links 0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 2
Number of hard-links 0
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
xorriso 1.5.4 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:/var/tmp/editliveos-4f84t81y/out/Fedora-Workstation-Live-x86_64-35FR-1.6-x86_64-20220511.0016.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 33.3g free
xorriso : WARNING : -volid text is too long for Joliet (32 > 16)
xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
Added to ISO image: directory '/'='/var/tmp/editliveos-4f84t81y/iso'
xorriso : UPDATE :      35 files added in 1 seconds
xorriso : UPDATE :      35 files added in 1 seconds
xorriso : NOTE : Copying to System Area: 432 bytes from file '/usr/share/syslinux/isohdpfx.bin'
libisofs: NOTE : Automatically adjusted MBR geometry to 1024/126/32
libisofs: NOTE : Aligned image size to cylinder size by 530 blocks
xorriso : UPDATE : Thank you for being patient. Working since 0 seconds.
xorriso : UPDATE :  27.91% done
xorriso : UPDATE :  86.10% done
ISO image produced: 1032192 sectors
Written to medium : 1032192 sectors at LBA 0
Writing to 'stdio:/var/tmp/editliveos-4f84t81y/out/Fedora-Workstation-Live-x86_64-35FR-1.6-x86_64-20220511.0016.iso' completed successfully.

Inserting md5sum into iso image...
md5 = 1f704523a25aeddd6080aeb9028631d1
Inserting fragment md5sums into iso image...
fragmd5 = e63b9fbbc161772f003a166599468c7a34fb6e52faf44d85b44e4ed32c2c
frags = 20
Setting supported flag to 0

Fedora-Workstation-Live-x86_64-35FR-1.6-x86_64-20220511.0016.iso saved to /var/home/mahdi/Vidéos/


LiveOS edit has ended.
Process duration: 00:18:08

```
1. I do not understand the usefulness for the step `"Enter (Ctrl D) to continue"` if I need to press Ctrl+D so that the command can continue it's execution, how can in embed it in a non-interactive shell script ?

**Comment by FGrose** [comment]
You may include the `--noshell` option to prevent the launching of a command shell in the new filesystem.

**Comment by mahdiaqallal** [comment]
I have tested the new .iso image that I have created :
Good news: The locale is in French and the timezone is correct (CEST)

This is progress ! Thanks for your help , I've tried to get that close unsuccessfully for many month now.

Bad news: the keyboard is in US and does not seem possible to be set... !

Although `localectl status` states that the keymap is `fr-oss` , the keymap is still in en_US
```

[liveuser@localhost-live ~]$ localectl status
   System Locale: LANG=fr_FR.UTF-8
       VC Keymap: fr-oss
      X11 Layout: n/a

```
[liveuser@localhost-live ~]$ uname -a
Linux localhost-live 5.14.10-300.fc35.x86_64 #1 SMP Thu Oct 7 20:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[liveuser@localhost-live ~]$ cat /etc/redhat-release 
11May2022-mahdi-Remix-Fedora-Workstation-Live 35
Fedora release 35 (Thirty Five)
[liveuser@localhost-live ~]$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
[liveuser@localhost-live ~]$ localectl set-keymap fr
[liveuser@localhost-live ~]$ localectl list-keymaps | grep -i fr
ca-fr-dvorak
ca-fr-legacy
ch-fr
ch-fr_mac
ch-fr_nodeadkeys
cm-french
dvorak-ca-fr
dvorak-fr
fr
fr-afnor
fr-azerty
fr-bepo
fr-bepo-latin9
fr-bepo_afnor
fr-bepo_latin9
fr-bre
fr-dvorak
fr-latin0
fr-latin1
fr-latin9
fr-latin9_nodeadkeys
fr-mac
fr-nodeadkeys
fr-oci
fr-old
fr-oss
fr-oss_latin9
fr-oss_nodeadkeys
fr-pc
fr-us
fr_CH
fr_CH-latin1
ma-french
mac-fr
mac-fr_CH-latin1
ml-fr-oss
sunt5-fr-latin1
vn-fr
```

**Comment by FGrose** [comment]
Without the --noshell option, `editliveos` launches a command shell change rooted (chrooted) in the newly mounted LiveOS filesystem:
```sh
Launching shell. Exit (Ctrl D) to continue.
-------------------------------------------
[root@fedora /]# 
```
The above shows the prompt for the root user in this newly launched shell.
At this point one may manually execute command line commands.  For example, one might update Fedora software in the new image by running `dnf upgrade`.

After manual operations are complete, the shell may be exited by pressing `Ctrl D`. At this point, the new filesystem is unmounted, squashed, and packaged into a new .iso image. (If the source image was a persistent LiveUSB, the LiveUSB image would be refreshed with all the changes that were made previously in the persistent overlay in addition to any changes made in the command shell just described.)

Alternatively, if one had tested a set of commands, the `--script PATH` option may be used to automatically run those commands  put into a shell script file at `PATH`.

**Comment by mahdiaqallal** [comment]
Very helpful.

Regarding the keymap issue:
Is there a workaround/update so that your edit for keyboard support:

> ```
>             kickstart.KeyboardConfig(editor._instroot).apply(ksh.keyboard)
> ```

Could "understand" the kickstart command
```
# Keyboard layouts
keyboard --vckeymap=fr-oss --xlayouts='fr (oss)'
```

As it did for Language and TimeZone ?

Best regards

**Comment by FGrose** [comment]
The kickstart.KeyboardConfig command does update `/etc/vconsole.conf`,
```sh
cat etc/vconsole.conf 
KEYMAP="fr-oss"
FONT="eurlatgr"
```
so perhaps the input is not parsed correctly or the bug is elsewhere in the keyboard control implementation.  I'm not familiar with that, sorry.

`--osmin_img` is an obsolete option for a feature Anaconda no longer supports.

**Comment by FGrose** [comment]
Keyboard mapping is first set in early boot code based on the vconsole.conf in the initramfs (initrd.img). We can trigger building a new initrd.img with the current version of editliveos by simulating a kernel version change with these commands in the change rooted shell:
```sh
mkdir usr/lib/modules/5.16
touch usr/lib/modules/5.16/vmlinuz
```
5.16 was chosen as a lower kernel version number than that in the source image.
With this and the kickstart keyboard entry, a new initrd.img will be built into the new .iso image after the shell exits.

A new `--initrd` option will be provided in a future version of editliveos.

**Comment by FGrose** [comment]
@mahdiaqallal
See also https://github.com/dracutdevs/dracut/blob/9cc7ceec1e9b4028d1a72bf51f9ea488d7ca11ac/man/dracut.usage.asc#keyboard-settings

You could add `rd.vconsole.font=eurlatgr rd.vconsole.keymap=fr-oss rd.locale.LANG=fr_FR.UTF-8` to your kernel command line.
