### ISSUE TITLE
editliveos fails with Fedora 37 ISO (expects Syslinux image)

### ISSUE THREAD

**Issue by alhashash** [livecd-tools/livecd-tools#256]
`editliveos` expects `/isolinux/` directory in the root. But, since Fedora 37 no longer uses SysLinux, it has no `/isolinux/` directory.

```
# editliveos --output Fedora-custom/ Fedora-Workstation-Live-x86_64-37-1.7.iso

Source image at 'Fedora-Workstation-Live-x86_64-37-1.7.iso'

           92,889,227 extra bytes set to be copied from the sources.
        5,509,627,691 bytes used in the LiveOS filesystem in Fedora-Workstation-Live-x86_64-37-1.7.iso.

        8,128,561,152 total bytes, root filesystem image size.

        8,519,426,006 bytes are estimated to be required for staging this build.

       64,760,414,208 bytes are available on /var/tmp for staging the build.
Copying the included folders and files.

LiveOS edit has ended.
Process duration: 00:00:07
Traceback (most recent call last):
  File "/usr/bin/editliveos", line 2754, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/editliveos", line 2626, in main
    editor._pre_mount(args.liveos, args.rootfsimg, args.overlay)
  File "/usr/bin/editliveos", line 809, in _pre_mount
    LiveImageCreator._base_on(self, base_on)
  File "/usr/lib/python3.11/site-packages/imgcreate/live.py", line 159, in _base_on
    files = [f for f in os.listdir(src) if pattern.search(f)
                        ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/editliveos-ew80bpo3/tmp-xf6o_n5j/isolinux/'
```

**Comment by Conan-Kudo** [comment]
@FGrose, can you take a look at this?
